# Generated by Django 5.1.4 on 2025-03-12 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='students',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
