# Generated by Django 5.1.4 on 2025-03-12 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_students_created_at_students_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
